version: '2'
services:
  angular:
    build: sms-crud-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./sms-crud-frontend:/app

  express:
    build: sms-crud-backend
    ports:
      - "3000:3000"